
/*
Auto-generated by CVXPYgen on April 06, 2025 at 16:44:25.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Psqrt(0, 0.00000000000000000000);
  cpg_update_Qsqrt(0, 141.42135623730951010657);
  cpg_update_Rsqrt(0, 0.00000000000000000000);
  cpg_update_x_init(0, 0.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<252; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<80; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<240; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<20; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<20; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<20; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<20; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<20; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<20; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<12; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }

  return 0;

}
