/*
 * This file was autogenerated by OSQP on Tue Apr  8 12:12:36 2025
 * 
 * This file contains a sample solver to run the embedded code.
 */

#include <stdio.h>
#include "osqp.h"
#include "workspace.h"

int main() {
  OSQPInt exitflag;

  printf( "Embedded test program for vector updates.\n");

  exitflag = osqp_solve( &solver );

  if( exitflag > 0 ) {
    printf( "  OSQP errored: %s\n", osqp_error_message(exitflag));
    return (int)exitflag;
  } else {
    printf( "  Solved workspace with no error.\n" );
  }
}
